vaadin-login-flow-integration-tests/pom.xml, vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/examples/Home.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/BasicIT.java, vaadin-login-flow-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginElement.java, vaadin-login-flow/pom.xml, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/Login.java, vaadin-login-flow/src/test/java/com/vaadin/flow/component/login/LoginTest.java
Add event for forget password button click, testbench element implementation, basic IT, basic unit test
Fixes #2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/5)
=> Implement basic integration

vaadin-login-flow-demo/src/main/java/com/vaadin/flow/component/login/vaadincom/LoginView.java, vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/examples/HomePtBR.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/BasicIT.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/I18nIT.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/Login.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginI18n.java, vaadin-login-flow/src/main/resources/i18n.json
Closes #3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/6)
=> Add support i18n and demo

vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/examples/Home.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/BasicIT.java, vaadin-login-flow-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginElement.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/Login.java, vaadin-login-flow/src/test/java/com/vaadin/flow/component/login/LoginTest.java
Event provides username and password
Closes #7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/16)
=> Handle login event

vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/examples/ActionView.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/BasicIT.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/Login.java
Closes #8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/18)
=> Add action property setter

vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/examples/DisabledLoginView.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/BasicIT.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/Login.java
Closes #10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/17)
=> Possibility to prevent firing submit events by setting disabled property

vaadin-login-flow-demo/src/main/java/com/vaadin/flow/component/login/vaadincom/LoginView.java, vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/examples/AbstractView.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/LoginIT.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/AbstractLogin.java
Fixes #9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/22)
=> Support error property

LICENSE, README.md, vaadin-login-flow-integration-tests/build-tools/package.json, vaadin-login-flow-integration-tests/src/main/webapp/frontend/bower.json, vaadin-login-flow-testbench/pom.xml, vaadin-login-flow-testbench/src/license/cval3/header.txt, vaadin-login-flow-testbench/src/license/cval3/license.txt, vaadin-login-flow-testbench/src/license/licenses.properties, vaadin-login-flow-testbench/src/main/java/com/vaadin/flow/component/login/testbench/Login.java, vaadin-login-flow-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginElement.java, vaadin-login-flow-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginOverlayElement.java, vaadin-login-flow/pom.xml, vaadin-login-flow/src/license/cval3/header.txt, vaadin-login-flow/src/license/cval3/license.txt, vaadin-login-flow/src/license/licenses.properties, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/AbstractLogin.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/Login.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginI18n.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/24)
=> Change component license to Apache 2.0

vaadin-login-flow-integration-tests/pom.xml, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/AbstractParallelTest.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/LoginIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/26)
=> Update saucelabs connect plugin

vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/BasicIT.java, vaadin-login-flow/src/main/resources/com/vaadin/flow/component/login/i18n.json, vaadin-login-flow/src/test/java/com/vaadin/flow/component/login/LoginI18nTest.java
related to https://github.com/vaadin/vaadin-login/issues/69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/31)
=> Make additional information empty by default

pom.xml, vaadin-login-flow-testbench/src/main/java/com/vaadin/flow/component/login/testbench/Login.java, vaadin-login-flow-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginElement.java, vaadin-login-flow-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginOverlayElement.java, vaadin-login-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/32)
=> Update to vaadin-login 1.0.0-alpha7

vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/examples/AbstractView.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/BasicIT.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/LoginIT.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/OverlayIT.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/AbstractLogin.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/30)
=> Support no-forgot-password property

vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/examples/AbstractView.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/LoginIT.java, vaadin-login-flow/pom.xml, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/AbstractLogin.java
Sync enabling the component when error is set
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/33)
=> Update component to alpha8

vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/examples/AbstractView.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/LoginFormIT.java, vaadin-login-flow-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginFormElement.java, vaadin-login-flow-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginOverlayElement.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/AbstractLogin.java
Do enabling on server side
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/34)
=> Prevent client side auto enabling on error set

vaadin-login-flow-integration-tests/pom.xml, vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/examples/OverlayView.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/OverlayIT.java, vaadin-login-flow/pom.xml, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
Set new title component only when the overlay is closed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/39)
=> Reset title component when setting string title

pom.xml, vaadin-login-flow-demo/pom.xml, vaadin-login-flow-integration-tests/pom.xml, vaadin-login-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/41)
=> Update to latest flow and component base

pom.xml, vaadin-login-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/44)
=> Use 1.0.0 vaadin-login webjar

pom.xml, vaadin-login-flow-demo/pom.xml, vaadin-login-flow-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/46)
=> use latest flow-component-base

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/51)
=> Add actual component to README

vaadin-login-flow-demo/src/main/java/com/vaadin/flow/component/login/vaadincom/LoginView.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/AbstractLogin.java
https://github.com/vaadin/vaadin-login-flow/issues/38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/50)
=> Added example showing how button is disabled/re-enabled.

vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginForm.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
Closes #38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/52)
=> Copied javadoc to subclasses of AbstractLogin

.gitignore, pom.xml, vaadin-login-flow-demo/pom.xml, vaadin-login-flow-integration-tests/pom.xml, vaadin-login-flow-integration-tests/src/main/java/com/vaadin/flow/component/login/examples/AbstractView.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/BasicIT.java, vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/LoginFormIT.java, vaadin-login-flow-testbench/pom.xml, vaadin-login-flow/pom.xml, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginForm.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
Part of flow#5489
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/55)
=> Migrate login project to NPM

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/56)
=> Use released versions in dependencies

vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginForm.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/57)
=> Import the WC unthemed version

.travis.yml, pom.xml, vaadin-login-flow-integration-tests/pom-bower-mode.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/59)
=> Add bower mode for testing

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/60)
=> Bump to flow 2.0 rc1

vaadin-login-flow-demo/pom.xml, vaadin-login-flow-integration-tests/pom-bower-mode.xml, vaadin-login-flow-integration-tests/pom.xml, vaadin-login-flow-testbench/pom.xml, vaadin-login-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/62)
=> Prepare release

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/63)
=> Bump testbench to 6.1.0.rc1

.travis.yml, vaadin-login-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/67)
=> Update login webjar to 1.0.1

vaadin-login-flow/pom.xml, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginForm.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/66)
=> Update login WC to 1.0.1

pom.xml, vaadin-login-flow-demo/pom.xml, vaadin-login-flow-integration-tests/pom-bower-mode.xml, vaadin-login-flow-integration-tests/pom.xml, vaadin-login-flow-testbench/pom.xml, vaadin-login-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/69)
=> Prepare rc2

vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/71)
=> Remove flow-component-renderer import

pom.xml, vaadin-login-flow-demo/pom.xml, vaadin-login-flow-integration-tests/pom-bower-mode.xml, vaadin-login-flow-integration-tests/pom.xml, vaadin-login-flow-testbench/pom.xml, vaadin-login-flow/pom.xml
Update flow-component-base
Update component dependencies
Update webjars
Remove unused dependencies in IT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/72)
=> Prepare for stable release

vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginI18n.java
Connected to https://github.com/vaadin/components-team-tasks/issues/483
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/79)
=> Update exception phrase

pom.xml, vaadin-login-flow-demo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/82)
=> Fix configuration for release

pom.xml, vaadin-login-flow-demo/pom.xml, vaadin-login-flow-integration-tests/pom-bower-mode.xml, vaadin-login-flow-integration-tests/pom.xml, vaadin-login-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/83)
=> Use snapshots

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/87)
=> Add version branches to travis (#86)

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/88)
=> Update button/textfield to latest snapshot

.gitignore, pom.xml, vaadin-login-flow-demo/pom.xml, vaadin-login-flow-integration-tests/pom.xml, vaadin-login-flow-testbench/pom.xml, vaadin-login-flow/pom.xml, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginForm.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-login-flow/89)
=> Update flow and wc versions

pom.xml, vaadin-login-flow-demo/pom.xml, vaadin-login-flow-integration-tests/pom-bower-mode.xml, vaadin-login-flow-integration-tests/pom.xml, vaadin-login-flow-testbench/pom.xml, vaadin-login-flow/pom.xml, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginForm.java, vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
* Bump snapshot version
* Bump flow-component-base (2.3-SNAPSHOT)
* Bump WC dependency
* Bump webjar dependencies
Part of vaadin/components-team-tasks#534
=> Bump versions for V14.3

vaadin-login-flow-demo/src/main/java/com/vaadin/flow/component/login/vaadincom/LoginView.java
This issue is for users to be able to use code correctly by copy-pasting
Depends on https://github.com/vaadin/flow/pull/8199/files
=> Adding missing method to Vaadin Login demos
